services:
  - type: web
    name: metamantenedor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: metamantenedor-db
          property: connectionString
databases:
  - name: metamantenedor-db
