name: Keep Metamantenedor Awake

on:
  # Ejecuta cada 5 minutos (hora UTC) y permite ejecución manual
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Warm up endpoints
        run: |
          set -e
          urls=(
            "https://metamantenedor.onrender.com/healthz"
            "https://metamantenedor.onrender.com/"
            "https://metamantenedor.onrender.com/form"
          )

          # Reintentos para cubrir el wake-up de Render (≈90 s por URL máx)
          for url in "${urls[@]}"; do
            echo "Pinging $url"
            ok=false
            for i in {1..6}; do
              if curl -fsS --max-time 15 "$url" >/dev/null; then
                ok=true
                echo "OK: $url"
                break
              else
                echo "Intento $i falló, esperando 15 s…"
                sleep 15
              fi
            done
            # Si no respondió 200, seguir igualmente (ya generó tráfico para despertar)
            if [ "$ok" = false ]; then
              echo "WARNING: $url no respondió 200 tras reintentos (continuando)."
            fi
          done
